name: 🚀 Deploy Erfindergeist Go-Child-Theme-Main

on:
  push:
    branches:    
      - 'main' 

jobs:
  web-deploy:
    name: 🎉 Deploy at https://erfindergeist.org/
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: erfindergeist.org
        username: ${{ secrets.FTP_USERNAME_MAIN }}
        password: ${{ secrets.FTP_PASSWORD_MAIN }}
        local-dir: ./
        protocol: ftps
        state-name: .ftp-deploy-sync-go-child-theme-state.json
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*